#!/bin/sh

MSG_FILE="$1"
MSG=$(cat "$MSG_FILE")

MIN_LENGTH=5

if [ ${#MSG} -lt $MIN_LENGTH ]; then
  echo "Commit message is too short!"
  echo "Minimum length is $MIN_LENGTH characters."
  echo "Your message: \"$MSG\""
  exit 1
fi

